# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_publicacion', models.DateTimeField(verbose_name='data publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('descricion', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='episodio',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss_feed.Programa'),
        ),
    ]
