# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='rss_link',
            field=models.CharField(default='NoLink', max_length=200),
            preserve_default=False,
        ),
    ]
