# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feed', '0002_programa_rss_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='ficheiro',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episodio',
            name='resumo',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
