# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feed', '0003_auto_20171220_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episodio',
            name='data_publicacion',
        ),
    ]
