# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-15 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feed', '0004_remove_episodio_data_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodio',
            name='resumo',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='programa',
            name='descricion',
            field=models.CharField(max_length=1000),
        ),
    ]
