# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-15 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feed', '0005_auto_20180115_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='autor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
