# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-19 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feed', '0006_auto_20180115_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodio',
            name='ficheiro',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='programa',
            name='rss_link',
            field=models.CharField(max_length=500),
        ),
    ]
